spring:
  card:
    datasource:
      url: jdbc:mysql://localhost:3306/card?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      password: password
      username: carduser
      driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
      username: cardadmin
      password: password
      url: jdbc:mysql://localhost:3306/card?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

  cardholder:
    datasource:
      url: jdbc:mysql://localhost:3306/cardholder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      password: password
      username: cardholderuser
      driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
      username: cardholderadmin
      password: password
      url: jdbc:mysql://localhost:3306/cardholder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

  pan:
    datasource:
      url: jdbc:mysql://localhost:3306/pan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      password: password
      username: panuser
      driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
      username: panadmin
      password: password
      url: jdbc:mysql://localhost:3306/pan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC